# Generated by Django 2.1.7 on 2019-06-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi.MyUser'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi.MyUser'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taxi.MyUser'),
        ),
    ]
